"""empty message

Revision ID: 0e2d62ba7328
Revises: c179c93580e2
Create Date: 2020-01-01 22:38:06.370763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2d62ba7328'
down_revision = 'c179c93580e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('mission', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mission', 'user', ['user_id'], ['id'])
    op.drop_column('mission', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('name', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'mission', type_='foreignkey')
    op.drop_column('mission', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
