"""add timestamp to mission

Revision ID: c7563990a6f5
Revises: 162d17799cde
Create Date: 2020-01-19 13:25:08.592586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7563990a6f5'
down_revision = '162d17799cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_mission_timestamp'), 'mission', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mission_timestamp'), table_name='mission')
    op.drop_column('mission', 'timestamp')
    # ### end Alembic commands ###
